### ISSUE TITLE
Didnt work 1.18.2

### ISSUE THREAD

**Issue by Aceplante** [Darkhax-Minecraft/What-The-Bucket#2]
I made a recipe to smelt a salmon bucket, and the bucket was still consumed

forge 1.18.2

**Comment by Darkhax** [comment]
Can you please upload your latest log file for the game?

**Comment by Darkhax** [comment]
Hello, after rereading what you wrote and checking the game code I have found the issue. The Furnace does not support container items for anything other than the fuel slot. So even vanilla water and milk buckets would be consumed in the top slot of the furnace. This bug is not fixed by this mod and would require changing the furnace logic in a way that is out of scope for this mod.
